Repository inference-labs-inc/omron-subnet, pull requests merged in 2025-02, with the labels that each got.

#54 Proof of computation RPC
  docs/running_on_staging.md
  makefile
  neurons/_validator/api/__init__.py
  neurons/_validator/api/cache.py
  neurons/_validator/core/request_pipeline.py
  neurons/_validator/models/poc_rpc_request.py
Labels: Next Release, WIP

#60 Setup Improvements
  README.md
  docs/running_on_mainnet.md
  docs/running_on_staging.md
  docs/running_on_testnet.md
  makefile
  neurons/cli_parser.py
  neurons/utils/pre_flight.py
  setup.sh
Labels: Needs QA

#64 Configure competition 1
  neurons/_miner/circuit_manager.py
  neurons/_miner/miner_session.py
  neurons/_validator/competitions/1/age.onnx
  neurons/_validator/competitions/1/competition_config.json
  neurons/_validator/competitions/1/data_processor.py
  neurons/_validator/competitions/1/input.json
  neurons/_validator/competitions/1/settings.json
  neurons/_validator/competitions/competition.py
  neurons/_validator/competitions/competition_manager.py
  neurons/_validator/competitions/models/neuron.py
  neurons/_validator/competitions/models/sota.py
  neurons/_validator/competitions/services/circuit_evaluator.py
  neurons/_validator/competitions/services/circuit_manager.py
  neurons/_validator/competitions/services/data_source.py
  neurons/_validator/competitions/services/onnx_runner.py
  neurons/_validator/competitions/services/sota_manager.py
  neurons/_validator/config/__init__.py
  neurons/_validator/core/validator_loop.py
  neurons/_validator/models/request_type.py
  neurons/_validator/scoring/score_manager.py
  neurons/scripts/create_competition_circuit.py
  neurons/utils/wandb_logger.py
  pyproject.toml
  requirements.txt
  uv.lock
Labels: Next Release

#67 Add competition docs
  docs/competitions/QUICKSTART.md
  docs/competitions/README.md
  neurons/_validator/core/validator_loop.py
Labels: Next Release

#75 Update validator loop
  neurons/_validator/core/validator_loop.py
Labels: Needs QA, Next Release

#80 Increase competition incentive
  neurons/deployment_layer/model_1e6fcdaea58741e7248b631718dda90398a17b294480beb12ce8232e27ca3bff/input.py
  neurons/deployment_layer/model_fa0d509d52abe2d1e809124f8aba46258a02f7253582f7b7f5a22e1e0bca0dfb/input.py
  neurons/incentive_mechanism.ipynb
Labels: Next Release

#86 Increase timeout for circuit file downloads
  neurons/_validator/competitions/services/circuit_manager.py
Labels: Next Release
